LDFLAGS=-ansi -pedantic

########################## TEST-1 #########################

test1_part1: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp tests/test1/part1.cpp -o tests/test1/part1
test1_part2: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp tests/test1/part2.cpp -o tests/test1/part2
test1_part3: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test1/part3.cpp -o tests/test1/part3
test1_part4: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp tests/test1/part4.cpp -o tests/test1/part4
test1_part5: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test1/part5.cpp -o tests/test1/part5
test1_part6: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test1/part6.cpp -o tests/test1/part6

run_test1_part1: ;./tests/test1/part1
run_test1_part2: ;./tests/test1/part2
run_test1_part3: ;./tests/test1/part3
run_test1_part4: ;./tests/test1/part4
run_test1_part5: ;./tests/test1/part5
run_test1_part6: ;./tests/test1/part6

valgrind_test1_part1: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test1/part1
valgrind_test1_part2: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test1/part2
valgrind_test1_part3: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test1/part3
valgrind_test1_part4: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test1/part4
valgrind_test1_part5: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test1/part5
valgrind_test1_part6: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test1/part6

########################## TEST-2 ##########################

test2_part1: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp tests/test2/part1.cpp -o tests/test2/part1
test2_part2: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp tests/test2/part2.cpp -o tests/test2/part2
test2_part3: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test2/part3.cpp -o tests/test2/part3
test2_part4: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test2/part4.cpp -o tests/test2/part4
test2_part5: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test2/part5.cpp -o tests/test2/part5
test2_part6: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp tests/test2/part6.cpp -o tests/test2/part6

run_test2_part1: ;./tests/test2/part1
run_test2_part2: ;./tests/test2/part2
run_test2_part3: ;./tests/test2/part3
run_test2_part4: ;./tests/test2/part4
run_test2_part5: ;./tests/test2/part5
run_test2_part6: ;./tests/test2/part6

valgrind_test2_part1: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test2/part1
valgrind_test2_part2: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test2/part2
valgrind_test2_part3: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test2/part3
valgrind_test2_part4: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test2/part4
valgrind_test2_part5: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test2/part5
valgrind_test2_part6: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test2/part6

########################## TEST-3 ##########################

test3_part1: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part1.cpp -o tests/test3/part1
test3_part2: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part2.cpp -o tests/test3/part2
test3_part3: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part3.cpp -o tests/test3/part3
test3_part4: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part4.cpp -o tests/test3/part4
test3_part5: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part5.cpp -o tests/test3/part5
test3_part6: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part6.cpp -o tests/test3/part6
test3_part7: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part7.cpp -o tests/test3/part7
test3_part8: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/Tissue.cpp tests/test3/part8.cpp -o tests/test3/part8

run_test3_part1: ;./tests/test3/part1
run_test3_part2: ;./tests/test3/part2
run_test3_part3: ;./tests/test3/part3
run_test3_part4: ;./tests/test3/part4
run_test3_part5: ;./tests/test3/part5
run_test3_part6: ;./tests/test3/part6
run_test3_part7: ;./tests/test3/part7
run_test3_part8: ;./tests/test3/part8

valgrind_test3_part1: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part1
valgrind_test3_part2: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part2
valgrind_test3_part3: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part3
valgrind_test3_part4: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part4
valgrind_test3_part5: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part5
valgrind_test3_part6: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part6
valgrind_test3_part7: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part7
valgrind_test3_part8: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test3/part8

########################## TEST-4 ##########################

test4_part1: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test4/part1.cpp -o tests/test4/part1
test4_part2: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test4/part2.cpp -o tests/test4/part2
test4_part3: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test4/part3.cpp -o tests/test4/part3
test4_part4: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Squadratic.cpp submission/Tissue.cpp tests/test4/part4.cpp -o tests/test4/part4
test4_part5: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Squadratic.cpp submission/Tissue.cpp tests/test4/part5.cpp -o tests/test4/part5
test4_part6: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Squadratic.cpp submission/Tissue.cpp tests/test4/part6.cpp -o tests/test4/part6
test4_part7: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Circular.cpp submission/Tissue.cpp tests/test4/part7.cpp -o tests/test4/part7
test4_part8: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Circular.cpp submission/Tissue.cpp tests/test4/part8.cpp -o tests/test4/part8
test4_part9: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Circular.cpp submission/Tissue.cpp tests/test4/part9.cpp -o tests/test4/part9

run_test4_part1: ;./tests/test4/part1
run_test4_part2: ;./tests/test4/part2
run_test4_part3: ;./tests/test4/part3
run_test4_part4: ;./tests/test4/part4
run_test4_part5: ;./tests/test4/part5
run_test4_part6: ;./tests/test4/part6
run_test4_part7: ;./tests/test4/part7
run_test4_part8: ;./tests/test4/part8
run_test4_part9: ;./tests/test4/part9

valgrind_test4_part1: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part1
valgrind_test4_part2: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part2
valgrind_test4_part3: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part3
valgrind_test4_part4: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part4
valgrind_test4_part5: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part5
valgrind_test4_part6: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part6
valgrind_test4_part7: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part7
valgrind_test4_part8: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part8
valgrind_test4_part9: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test4/part9

########################## TEST-5 ##########################

test5_part1: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test5/part1.cpp -o tests/test5/part1
test5_part2: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test5/part2.cpp -o tests/test5/part2
test5_part3: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Squadratic.cpp submission/Tissue.cpp tests/test5/part3.cpp -o tests/test5/part3
test5_part4: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Squadratic.cpp submission/Tissue.cpp tests/test5/part4.cpp -o tests/test5/part4
test5_part5: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Squadratic.cpp submission/Tissue.cpp tests/test5/part5.cpp -o tests/test5/part5
test5_part6: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Circular.cpp submission/Tissue.cpp tests/test5/part6.cpp -o tests/test5/part6
test5_part7: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Circular.cpp submission/Tissue.cpp tests/test5/part7.cpp -o tests/test5/part7

run_test5_part1: ;./tests/test5/part1 tests/test5/input_cells.txt
run_test5_part2: ;./tests/test5/part2 tests/test5/input_cells.txt
run_test5_part3: ;./tests/test5/part3 tests/test5/input_cells.txt
run_test5_part4: ;./tests/test5/part4 tests/test5/input_cells.txt
run_test5_part5: ;./tests/test5/part5 tests/test5/input_cells.txt
run_test5_part6: ;./tests/test5/part6 tests/test5/input_cells.txt
run_test5_part7: ;./tests/test5/part7 tests/test5/input_cells.txt

valgrind_test5_part1: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part1 tests/test5/input_cells.txt
valgrind_test5_part2: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part2 tests/test5/input_cells.txt
valgrind_test5_part3: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part3 tests/test5/input_cells.txt
valgrind_test5_part4: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part4 tests/test5/input_cells.txt
valgrind_test5_part5: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part5 tests/test5/input_cells.txt
valgrind_test5_part6: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part6 tests/test5/input_cells.txt
valgrind_test5_part7: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test5/part7 tests/test5/input_cells.txt

########################## TEST-6 ##########################

test6_part1: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test6/part1.cpp -o tests/test6/part1
test6_part2: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test6/part2.cpp -o tests/test6/part2
test6_part3: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/NucleoBase.cpp submission/Triangular.cpp submission/Tissue.cpp tests/test6/part3.cpp -o tests/test6/part3
test6_part4: ; g++ $(LDFLAGS) grader/common.cpp submission/Particle.cpp submission/Wall.cpp submission/CurvyWall.cpp submission/Cell.cpp submission/MicroOrganism.cpp submission/Circular.cpp submission/Tissue.cpp tests/test6/part4.cpp -o tests/test6/part4

run_test6_part1: ;./tests/test6/part1
run_test6_part2: ;./tests/test6/part2
run_test6_part3: ;./tests/test6/part3
run_test6_part4: ;./tests/test6/part4

valgrind_test6_part1: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test6/part1
valgrind_test6_part2: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test6/part2
valgrind_test6_part3: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test6/part3
valgrind_test6_part4: ; valgrind --leak-check=full --error-exitcode=142 ./tests/test6/part4

########################## CLEAN-UP ##########################

clean: ; rm -rf tests/test?/part?
